### PR TITLE
Updated to 1.21

### PR DESCRIPTION
**Pull request by SaiCode-DEV**
Hello There!

I updated the version to 1.21.

It crashed because of:

```
 old:      model.renderToBuffer(stack, consumer, light, OverlayTexture.NO_OVERLAY, 1F, 1F, 1F, alpha);
 new:      model.renderToBuffer(stack, consumer, light, OverlayTexture.NO_OVERLAY, 0xffffffff);
```

I also added build.yml which automatically builds and if you uncomment it automatically deploys it to Modrinth!

Only thing you have to change is the version number still!

### CODE REVIEW

**Comment by SaiCode-DEV** [comment]
ezgif com-optimize

**Comment by SaiCode-DEV** [comment]
Can you perhaps also add the option to ignore the applied dye and set it to white instead? 

With Diamond trim material, a lot seems wrong.

**Comment by SaiCode-DEV** [comment]
p.s. Wenn du hilfe brauchst mit dem modrinth auto deploy, sag einfach auf DC (saicode) bescheid. 
hab gerade erst gesehen dass du Deutsch bist.

**Review by xxNiklasxx08 — APPROVED** [review]
Thank you for your work!

**Pull request merged**
